#ifndef PSK_MODES_H
#define PSK_MODES_H

// Extracted from https://www.adif.org/317/ADIF_317.htm#Mode_Enumeration

// AM
#define PSK_MODE_AM "AM"

// ARDOP
#define PSK_MODE_ARDOP "ARDOP"

// ATV
#define PSK_MODE_ATV "ATV"

// CHIP
#define PSK_MODE_CHIP "CHIP"
#define PSK_MODE_CHIP64 "CHIP64"
#define PSK_MODE_CHIP128 "CHIP128"

// CLO
#define PSK_MODE_CLO "CLO"

// CONTESTI
#define PSK_MODE_CONTESTI "CONTESTI"

// CW
#define PSK_MODE_CW "CW"
#define PSK_MODE_PCW "PCW"

// DIGITALVOICE
#define PSK_MODE_DIGITALVOICE "DIGITALVOICE"
#define PSK_MODE_C4FM "C4FM"
#define PSK_MODE_DSTAR "DSTAR"
#define PSK_MODE_DMR "DMR"
#define PSK_MODE_FREEDV "FREEDV"
#define PSK_MODE_M17 "M17"

// DOMINO
#define PSK_MODE_DOMINO "DOMINO"
#define PSK_MODE_DOM_M "DOM-M"
#define PSK_MODE_DOM4 "DOM4"
#define PSK_MODE_DOM5 "DOM5"
#define PSK_MODE_DOM8 "DOM8"
#define PSK_MODE_DOM11 "DOM11"
#define PSK_MODE_DOM16 "DOM16"
#define PSK_MODE_DOM22 "DOM22"
#define PSK_MODE_DOM44 "DOM44"
#define PSK_MODE_DOM88 "DOM88"
#define PSK_MODE_DOMINOEX "DOMINOEX"
#define PSK_MODE_DOMINOF "DOMINOF"

// DYNAMIC
#define PSK_MODE_DYNAMIC "DYNAMIC"
#define PSK_MODE_FREEDATA "FREEDATA"
#define PSK_MODE_VARA_HF "VARA HF"
#define PSK_MODE_VARA_SATELLITE "VARA SATELLITE"
#define PSK_MODE_VARA_FM_1200 "VARA FM 1200"
#define PSK_MODE_VARA_FM_9600 "VARA FM 9600"

// FAX
#define PSK_MODE_FAX "FAX"

// FM
#define PSK_MODE_FM "FM"

// FSK441
#define PSK_MODE_FSK441 "FSK441"

// FSK
#define PSK_MODE_FSK "FSK"
#define PSK_MODE_SCAMP_FAST "SCAMP_FAST"
#define PSK_MODE_SCAMP_SLOW "SCAMP_SLOW"
#define PSK_MODE_SCAMP_VSLOW "SCAMP_VSLOW"

// FT8
#define PSK_MODE_FT8 "FT8"

// HELL
#define PSK_MODE_HELL "HELL"
#define PSK_MODE_FMHELL "FMHELL"
#define PSK_MODE_FSKH105 "FSKH105"
#define PSK_MODE_FSKH245 "FSKH245"
#define PSK_MODE_FSKHELL "FSKHELL"
#define PSK_MODE_HELL80 "HELL80"
#define PSK_MODE_HELLX5 "HELLX5"
#define PSK_MODE_HELLX9 "HELLX9"
#define PSK_MODE_HFSK "HFSK"
#define PSK_MODE_PSKHELL "PSKHELL"
#define PSK_MODE_SLOWHELL "SLOWHELL"

// ISCAT
#define PSK_MODE_ISCAT "ISCAT"
#define PSK_MODE_ISCAT_A "ISCAT-A"
#define PSK_MODE_ISCAT_B "ISCAT-B"

// JT4
#define PSK_MODE_JT4 "JT4"
#define PSK_MODE_JT4A "JT4A"
#define PSK_MODE_JT4B "JT4B"
#define PSK_MODE_JT4C "JT4C"
#define PSK_MODE_JT4D "JT4D"
#define PSK_MODE_JT4E "JT4E"
#define PSK_MODE_JT4F "JT4F"
#define PSK_MODE_JT4G "JT4G"

// JT6M
#define PSK_MODE_JT6M "JT6M"

// JT9
#define PSK_MODE_JT9 "JT9"
#define PSK_MODE_JT9_1 "JT9-1"
#define PSK_MODE_JT9_2 "JT9-2"
#define PSK_MODE_JT9_5 "JT9-5"
#define PSK_MODE_JT9_10 "JT9-10"
#define PSK_MODE_JT9_30 "JT9-30"
#define PSK_MODE_JT9A "JT9A"
#define PSK_MODE_JT9B "JT9B"
#define PSK_MODE_JT9C "JT9C"
#define PSK_MODE_JT9D "JT9D"
#define PSK_MODE_JT9E "JT9E"
#define PSK_MODE_JT9E_FAST "JT9E FAST"
#define PSK_MODE_JT9F "JT9F"
#define PSK_MODE_JT9F_FAST "JT9F FAST"
#define PSK_MODE_JT9G "JT9G"
#define PSK_MODE_JT9G_FAST "JT9G FAST"
#define PSK_MODE_JT9H "JT9H"
#define PSK_MODE_JT9H_FAST "JT9H FAST"

// JT44
#define PSK_MODE_JT44 "JT44"

// JT65
#define PSK_MODE_JT65 "JT65"
#define PSK_MODE_JT65A "JT65A"
#define PSK_MODE_JT65B "JT65B"
#define PSK_MODE_JT65B2 "JT65B2"
#define PSK_MODE_JT65C "JT65C"
#define PSK_MODE_JT65C2 "JT65C2"

// MFSK
#define PSK_MODE_MFSK "MFSK"
#define PSK_MODE_FSQCALL "FSQCALL"
#define PSK_MODE_FST4 "FST4"
#define PSK_MODE_FST4W "FST4W"
#define PSK_MODE_FT2 "FT2"
#define PSK_MODE_FT4 "FT4"
#define PSK_MODE_JS8 "JS8"
#define PSK_MODE_JTMS "JTMS"
#define PSK_MODE_MFSK4 "MFSK4"
#define PSK_MODE_MFSK8 "MFSK8"
#define PSK_MODE_MFSK11 "MFSK11"
#define PSK_MODE_MFSK16 "MFSK16"
#define PSK_MODE_MFSK22 "MFSK22"
#define PSK_MODE_MFSK31 "MFSK31"
#define PSK_MODE_MFSK32 "MFSK32"
#define PSK_MODE_MFSK64 "MFSK64"
#define PSK_MODE_MFSK64L "MFSK64L"
#define PSK_MODE_MFSK128 "MFSK128"
#define PSK_MODE_MFSK128L "MFSK128L"
#define PSK_MODE_Q65 "Q65"

// MSK144
#define PSK_MODE_MSK144 "MSK144"

// MTONE
#define PSK_MODE_MTONE "MTONE"
#define PSK_MODE_SCAMP_OO "SCAMP_OO"
#define PSK_MODE_SCAMP_OO_SLW "SCAMP_OO_SLW"

// MT63
#define PSK_MODE_MT63 "MT63"

// OFDM
#define PSK_MODE_OFDM "OFDM"
#define PSK_MODE_RIBBIT_PIX "RIBBIT_PIX"
#define PSK_MODE_RIBBIT_SMS "RIBBIT_SMS"

// OLIVIA
#define PSK_MODE_OLIVIA "OLIVIA"
#define PSK_MODE_OLIVIA_4_125 "OLIVIA 4/125"
#define PSK_MODE_OLIVIA_4_250 "OLIVIA 4/250"
#define PSK_MODE_OLIVIA_8_250 "OLIVIA 8/250"
#define PSK_MODE_OLIVIA_8_500 "OLIVIA 8/500"
#define PSK_MODE_OLIVIA_16_500 "OLIVIA 16/500"
#define PSK_MODE_OLIVIA_16_1000 "OLIVIA 16/1000"
#define PSK_MODE_OLIVIA_32_1000 "OLIVIA 32/1000"

// OPERA
#define PSK_MODE_OPERA "OPERA"
#define PSK_MODE_OPERA_BEACON "OPERA-BEACON"
#define PSK_MODE_OPERA_QSO "OPERA-QSO"

// PAC
#define PSK_MODE_PAC "PAC"
#define PSK_MODE_PAC2 "PAC2"
#define PSK_MODE_PAC3 "PAC3"
#define PSK_MODE_PAC4 "PAC4"

// PAX
#define PSK_MODE_PAX "PAX"
#define PSK_MODE_PAX2 "PAX2"

// PKT
#define PSK_MODE_PKT "PKT"

// PSK
#define PSK_MODE_PSK "PSK"
#define PSK_MODE_8PSK125 "8PSK125"
#define PSK_MODE_8PSK125F "8PSK125F"
#define PSK_MODE_8PSK125FL "8PSK125FL"
#define PSK_MODE_8PSK250 "8PSK250"
#define PSK_MODE_8PSK250F "8PSK250F"
#define PSK_MODE_8PSK250FL "8PSK250FL"
#define PSK_MODE_8PSK500 "8PSK500"
#define PSK_MODE_8PSK500F "8PSK500F"
#define PSK_MODE_8PSK1000 "8PSK1000"
#define PSK_MODE_8PSK1000F "8PSK1000F"
#define PSK_MODE_8PSK1200F "8PSK1200F"
#define PSK_MODE_FSK31 "FSK31"
#define PSK_MODE_PSK10 "PSK10"
#define PSK_MODE_PSK31 "PSK31"
#define PSK_MODE_PSK63 "PSK63"
#define PSK_MODE_PSK63F "PSK63F"
#define PSK_MODE_PSK63RC4 "PSK63RC4"
#define PSK_MODE_PSK63RC5 "PSK63RC5"
#define PSK_MODE_PSK63RC10 "PSK63RC10"
#define PSK_MODE_PSK63RC20 "PSK63RC20"
#define PSK_MODE_PSK63RC32 "PSK63RC32"
#define PSK_MODE_PSK125 "PSK125"
#define PSK_MODE_PSK125C12 "PSK125C12"
#define PSK_MODE_PSK125R "PSK125R"
#define PSK_MODE_PSK125RC10 "PSK125RC10"
#define PSK_MODE_PSK125RC12 "PSK125RC12"
#define PSK_MODE_PSK125RC16 "PSK125RC16"
#define PSK_MODE_PSK125RC4 "PSK125RC4"
#define PSK_MODE_PSK125RC5 "PSK125RC5"
#define PSK_MODE_PSK250 "PSK250"
#define PSK_MODE_PSK250C6 "PSK250C6"
#define PSK_MODE_PSK250R "PSK250R"
#define PSK_MODE_PSK250RC2 "PSK250RC2"
#define PSK_MODE_PSK250RC3 "PSK250RC3"
#define PSK_MODE_PSK250RC5 "PSK250RC5"
#define PSK_MODE_PSK250RC6 "PSK250RC6"
#define PSK_MODE_PSK250RC7 "PSK250RC7"
#define PSK_MODE_PSK500 "PSK500"
#define PSK_MODE_PSK500C2 "PSK500C2"
#define PSK_MODE_PSK500C4 "PSK500C4"
#define PSK_MODE_PSK500R "PSK500R"
#define PSK_MODE_PSK500RC2 "PSK500RC2"
#define PSK_MODE_PSK500RC3 "PSK500RC3"
#define PSK_MODE_PSK500RC4 "PSK500RC4"
#define PSK_MODE_PSK800C2 "PSK800C2"
#define PSK_MODE_PSK800RC2 "PSK800RC2"
#define PSK_MODE_PSK1000 "PSK1000"
#define PSK_MODE_PSK1000C2 "PSK1000C2"
#define PSK_MODE_PSK1000R "PSK1000R"
#define PSK_MODE_PSK1000RC2 "PSK1000RC2"
#define PSK_MODE_PSKAM10 "PSKAM10"
#define PSK_MODE_PSKAM31 "PSKAM31"
#define PSK_MODE_PSKAM50 "PSKAM50"
#define PSK_MODE_PSKFEC31 "PSKFEC31"
#define PSK_MODE_QPSK31 "QPSK31"
#define PSK_MODE_QPSK63 "QPSK63"
#define PSK_MODE_QPSK125 "QPSK125"
#define PSK_MODE_QPSK250 "QPSK250"
#define PSK_MODE_QPSK500 "QPSK500"
#define PSK_MODE_SIM31 "SIM31"

// PSK2K
#define PSK_MODE_PSK2K "PSK2K"

// Q15
#define PSK_MODE_Q15 "Q15"

// QRA64
#define PSK_MODE_QRA64 "QRA64"
#define PSK_MODE_QRA64A "QRA64A"
#define PSK_MODE_QRA64B "QRA64B"
#define PSK_MODE_QRA64C "QRA64C"
#define PSK_MODE_QRA64D "QRA64D"
#define PSK_MODE_QRA64E "QRA64E"

// ROS
#define PSK_MODE_ROS "ROS"
#define PSK_MODE_ROS_EME "ROS-EME"
#define PSK_MODE_ROS_HF "ROS-HF"
#define PSK_MODE_ROS_MF "ROS-MF"

// RTTY
#define PSK_MODE_RTTY "RTTY"
#define PSK_MODE_ASCI "ASCI"

// RTTYM
#define PSK_MODE_RTTYM "RTTYM"

// SSB
#define PSK_MODE_SSB "SSB"
#define PSK_MODE_LSB "LSB"
#define PSK_MODE_USB "USB"

// SSTV
#define PSK_MODE_SSTV "SSTV"

// T10
#define PSK_MODE_T10 "T10"

// THOR
#define PSK_MODE_THOR "THOR"
#define PSK_MODE_THOR_M "THOR-M"
#define PSK_MODE_THOR4 "THOR4"
#define PSK_MODE_THOR5 "THOR5"
#define PSK_MODE_THOR8 "THOR8"
#define PSK_MODE_THOR11 "THOR11"
#define PSK_MODE_THOR16 "THOR16"
#define PSK_MODE_THOR22 "THOR22"
#define PSK_MODE_THOR25X4 "THOR25X4"
#define PSK_MODE_THOR50X1 "THOR50X1"
#define PSK_MODE_THOR50X2 "THOR50X2"
#define PSK_MODE_THOR100 "THOR100"

// THRB
#define PSK_MODE_THRB "THRB"
#define PSK_MODE_THRBX "THRBX"
#define PSK_MODE_THRBX1 "THRBX1"
#define PSK_MODE_THRBX2 "THRBX2"
#define PSK_MODE_THRBX4 "THRBX4"
#define PSK_MODE_THROB1 "THROB1"
#define PSK_MODE_THROB2 "THROB2"
#define PSK_MODE_THROB4 "THROB4"

// TOR
#define PSK_MODE_TOR "TOR"
#define PSK_MODE_AMTORFEC "AMTORFEC"
#define PSK_MODE_GTOR "GTOR"
#define PSK_MODE_NAVTEX "NAVTEX"
#define PSK_MODE_SITORB "SITORB"

// V4
#define PSK_MODE_V4 "V4"

// VOI
#define PSK_MODE_VOI "VOI"

// WINMOR
#define PSK_MODE_WINMOR "WINMOR"

// WSPR
#define PSK_MODE_WSPR "WSPR"

#endif
