#ifndef PREPC_MODES_H
#define PREPC_MODES_H

// Extracted from https://www.adif.org/317/ADIF_317.htm#Mode_Enumeration

// AM
#define PREPC_MODE_AM "AM"

// ARDOP
#define PREPC_MODE_ARDOP "ARDOP"

// ATV
#define PREPC_MODE_ATV "ATV"

// CHIP
#define PREPC_MODE_CHIP "CHIP"
#define PREPC_MODE_CHIP64 "CHIP64"
#define PREPC_MODE_CHIP128 "CHIP128"

// CLO
#define PREPC_MODE_CLO "CLO"

// CONTESTI
#define PREPC_MODE_CONTESTI "CONTESTI"

// CW
#define PREPC_MODE_CW "CW"
#define PREPC_MODE_PCW "PCW"

// DIGITALVOICE
#define PREPC_MODE_DIGITALVOICE "DIGITALVOICE"
#define PREPC_MODE_C4FM "C4FM"
#define PREPC_MODE_DSTAR "DSTAR"
#define PREPC_MODE_DMR "DMR"
#define PREPC_MODE_FREEDV "FREEDV"
#define PREPC_MODE_M17 "M17"

// DOMINO
#define PREPC_MODE_DOMINO "DOMINO"
#define PREPC_MODE_DOM_M "DOM-M"
#define PREPC_MODE_DOM4 "DOM4"
#define PREPC_MODE_DOM5 "DOM5"
#define PREPC_MODE_DOM8 "DOM8"
#define PREPC_MODE_DOM11 "DOM11"
#define PREPC_MODE_DOM16 "DOM16"
#define PREPC_MODE_DOM22 "DOM22"
#define PREPC_MODE_DOM44 "DOM44"
#define PREPC_MODE_DOM88 "DOM88"
#define PREPC_MODE_DOMINOEX "DOMINOEX"
#define PREPC_MODE_DOMINOF "DOMINOF"

// DYNAMIC
#define PREPC_MODE_DYNAMIC "DYNAMIC"
#define PREPC_MODE_FREEDATA "FREEDATA"
#define PREPC_MODE_VARA_HF "VARA HF"
#define PREPC_MODE_VARA_SATELLITE "VARA SATELLITE"
#define PREPC_MODE_VARA_FM_1200 "VARA FM 1200"
#define PREPC_MODE_VARA_FM_9600 "VARA FM 9600"

// FAX
#define PREPC_MODE_FAX "FAX"

// FM
#define PREPC_MODE_FM "FM"

// FSK441
#define PREPC_MODE_FSK441 "FSK441"

// FSK
#define PREPC_MODE_FSK "FSK"
#define PREPC_MODE_SCAMP_FAST "SCAMP_FAST"
#define PREPC_MODE_SCAMP_SLOW "SCAMP_SLOW"
#define PREPC_MODE_SCAMP_VSLOW "SCAMP_VSLOW"

// FT8
#define PREPC_MODE_FT8 "FT8"

// HELL
#define PREPC_MODE_HELL "HELL"
#define PREPC_MODE_FMHELL "FMHELL"
#define PREPC_MODE_FSKH105 "FSKH105"
#define PREPC_MODE_FSKH245 "FSKH245"
#define PREPC_MODE_FSKHELL "FSKHELL"
#define PREPC_MODE_HELL80 "HELL80"
#define PREPC_MODE_HELLX5 "HELLX5"
#define PREPC_MODE_HELLX9 "HELLX9"
#define PREPC_MODE_HFSK "HFSK"
#define PREPC_MODE_PREPCHELL "PREPCHELL"
#define PREPC_MODE_SLOWHELL "SLOWHELL"

// ISCAT
#define PREPC_MODE_ISCAT "ISCAT"
#define PREPC_MODE_ISCAT_A "ISCAT-A"
#define PREPC_MODE_ISCAT_B "ISCAT-B"

// JT4
#define PREPC_MODE_JT4 "JT4"
#define PREPC_MODE_JT4A "JT4A"
#define PREPC_MODE_JT4B "JT4B"
#define PREPC_MODE_JT4C "JT4C"
#define PREPC_MODE_JT4D "JT4D"
#define PREPC_MODE_JT4E "JT4E"
#define PREPC_MODE_JT4F "JT4F"
#define PREPC_MODE_JT4G "JT4G"

// JT6M
#define PREPC_MODE_JT6M "JT6M"

// JT9
#define PREPC_MODE_JT9 "JT9"
#define PREPC_MODE_JT9_1 "JT9-1"
#define PREPC_MODE_JT9_2 "JT9-2"
#define PREPC_MODE_JT9_5 "JT9-5"
#define PREPC_MODE_JT9_10 "JT9-10"
#define PREPC_MODE_JT9_30 "JT9-30"
#define PREPC_MODE_JT9A "JT9A"
#define PREPC_MODE_JT9B "JT9B"
#define PREPC_MODE_JT9C "JT9C"
#define PREPC_MODE_JT9D "JT9D"
#define PREPC_MODE_JT9E "JT9E"
#define PREPC_MODE_JT9E_FAST "JT9E FAST"
#define PREPC_MODE_JT9F "JT9F"
#define PREPC_MODE_JT9F_FAST "JT9F FAST"
#define PREPC_MODE_JT9G "JT9G"
#define PREPC_MODE_JT9G_FAST "JT9G FAST"
#define PREPC_MODE_JT9H "JT9H"
#define PREPC_MODE_JT9H_FAST "JT9H FAST"

// JT44
#define PREPC_MODE_JT44 "JT44"

// JT65
#define PREPC_MODE_JT65 "JT65"
#define PREPC_MODE_JT65A "JT65A"
#define PREPC_MODE_JT65B "JT65B"
#define PREPC_MODE_JT65B2 "JT65B2"
#define PREPC_MODE_JT65C "JT65C"
#define PREPC_MODE_JT65C2 "JT65C2"

// MFSK
#define PREPC_MODE_MFSK "MFSK"
#define PREPC_MODE_FSQCALL "FSQCALL"
#define PREPC_MODE_FST4 "FST4"
#define PREPC_MODE_FST4W "FST4W"
#define PREPC_MODE_FT2 "FT2"
#define PREPC_MODE_FT4 "FT4"
#define PREPC_MODE_JS8 "JS8"
#define PREPC_MODE_JTMS "JTMS"
#define PREPC_MODE_MFSK4 "MFSK4"
#define PREPC_MODE_MFSK8 "MFSK8"
#define PREPC_MODE_MFSK11 "MFSK11"
#define PREPC_MODE_MFSK16 "MFSK16"
#define PREPC_MODE_MFSK22 "MFSK22"
#define PREPC_MODE_MFSK31 "MFSK31"
#define PREPC_MODE_MFSK32 "MFSK32"
#define PREPC_MODE_MFSK64 "MFSK64"
#define PREPC_MODE_MFSK64L "MFSK64L"
#define PREPC_MODE_MFSK128 "MFSK128"
#define PREPC_MODE_MFSK128L "MFSK128L"
#define PREPC_MODE_Q65 "Q65"

// MSK144
#define PREPC_MODE_MSK144 "MSK144"

// MTONE
#define PREPC_MODE_MTONE "MTONE"
#define PREPC_MODE_SCAMP_OO "SCAMP_OO"
#define PREPC_MODE_SCAMP_OO_SLW "SCAMP_OO_SLW"

// MT63
#define PREPC_MODE_MT63 "MT63"

// OFDM
#define PREPC_MODE_OFDM "OFDM"
#define PREPC_MODE_RIBBIT_PIX "RIBBIT_PIX"
#define PREPC_MODE_RIBBIT_SMS "RIBBIT_SMS"

// OLIVIA
#define PREPC_MODE_OLIVIA "OLIVIA"
#define PREPC_MODE_OLIVIA_4_125 "OLIVIA 4/125"
#define PREPC_MODE_OLIVIA_4_250 "OLIVIA 4/250"
#define PREPC_MODE_OLIVIA_8_250 "OLIVIA 8/250"
#define PREPC_MODE_OLIVIA_8_500 "OLIVIA 8/500"
#define PREPC_MODE_OLIVIA_16_500 "OLIVIA 16/500"
#define PREPC_MODE_OLIVIA_16_1000 "OLIVIA 16/1000"
#define PREPC_MODE_OLIVIA_32_1000 "OLIVIA 32/1000"

// OPERA
#define PREPC_MODE_OPERA "OPERA"
#define PREPC_MODE_OPERA_BEACON "OPERA-BEACON"
#define PREPC_MODE_OPERA_QSO "OPERA-QSO"

// PAC
#define PREPC_MODE_PAC "PAC"
#define PREPC_MODE_PAC2 "PAC2"
#define PREPC_MODE_PAC3 "PAC3"
#define PREPC_MODE_PAC4 "PAC4"

// PAX
#define PREPC_MODE_PAX "PAX"
#define PREPC_MODE_PAX2 "PAX2"

// PKT
#define PREPC_MODE_PKT "PKT"

// PREPC
#define PREPC_MODE_PREPC "PREPC"
#define PREPC_MODE_8PREPC125 "8PREPC125"
#define PREPC_MODE_8PREPC125F "8PREPC125F"
#define PREPC_MODE_8PREPC125FL "8PREPC125FL"
#define PREPC_MODE_8PREPC250 "8PREPC250"
#define PREPC_MODE_8PREPC250F "8PREPC250F"
#define PREPC_MODE_8PREPC250FL "8PREPC250FL"
#define PREPC_MODE_8PREPC500 "8PREPC500"
#define PREPC_MODE_8PREPC500F "8PREPC500F"
#define PREPC_MODE_8PREPC1000 "8PREPC1000"
#define PREPC_MODE_8PREPC1000F "8PREPC1000F"
#define PREPC_MODE_8PREPC1200F "8PREPC1200F"
#define PREPC_MODE_FSK31 "FSK31"
#define PREPC_MODE_PREPC10 "PREPC10"
#define PREPC_MODE_PREPC31 "PREPC31"
#define PREPC_MODE_PREPC63 "PREPC63"
#define PREPC_MODE_PREPC63F "PREPC63F"
#define PREPC_MODE_PREPC63RC4 "PREPC63RC4"
#define PREPC_MODE_PREPC63RC5 "PREPC63RC5"
#define PREPC_MODE_PREPC63RC10 "PREPC63RC10"
#define PREPC_MODE_PREPC63RC20 "PREPC63RC20"
#define PREPC_MODE_PREPC63RC32 "PREPC63RC32"
#define PREPC_MODE_PREPC125 "PREPC125"
#define PREPC_MODE_PREPC125C12 "PREPC125C12"
#define PREPC_MODE_PREPC125R "PREPC125R"
#define PREPC_MODE_PREPC125RC10 "PREPC125RC10"
#define PREPC_MODE_PREPC125RC12 "PREPC125RC12"
#define PREPC_MODE_PREPC125RC16 "PREPC125RC16"
#define PREPC_MODE_PREPC125RC4 "PREPC125RC4"
#define PREPC_MODE_PREPC125RC5 "PREPC125RC5"
#define PREPC_MODE_PREPC250 "PREPC250"
#define PREPC_MODE_PREPC250C6 "PREPC250C6"
#define PREPC_MODE_PREPC250R "PREPC250R"
#define PREPC_MODE_PREPC250RC2 "PREPC250RC2"
#define PREPC_MODE_PREPC250RC3 "PREPC250RC3"
#define PREPC_MODE_PREPC250RC5 "PREPC250RC5"
#define PREPC_MODE_PREPC250RC6 "PREPC250RC6"
#define PREPC_MODE_PREPC250RC7 "PREPC250RC7"
#define PREPC_MODE_PREPC500 "PREPC500"
#define PREPC_MODE_PREPC500C2 "PREPC500C2"
#define PREPC_MODE_PREPC500C4 "PREPC500C4"
#define PREPC_MODE_PREPC500R "PREPC500R"
#define PREPC_MODE_PREPC500RC2 "PREPC500RC2"
#define PREPC_MODE_PREPC500RC3 "PREPC500RC3"
#define PREPC_MODE_PREPC500RC4 "PREPC500RC4"
#define PREPC_MODE_PREPC800C2 "PREPC800C2"
#define PREPC_MODE_PREPC800RC2 "PREPC800RC2"
#define PREPC_MODE_PREPC1000 "PREPC1000"
#define PREPC_MODE_PREPC1000C2 "PREPC1000C2"
#define PREPC_MODE_PREPC1000R "PREPC1000R"
#define PREPC_MODE_PREPC1000RC2 "PREPC1000RC2"
#define PREPC_MODE_PREPCAM10 "PREPCAM10"
#define PREPC_MODE_PREPCAM31 "PREPCAM31"
#define PREPC_MODE_PREPCAM50 "PREPCAM50"
#define PREPC_MODE_PREPCFEC31 "PREPCFEC31"
#define PREPC_MODE_QPREPC31 "QPREPC31"
#define PREPC_MODE_QPREPC63 "QPREPC63"
#define PREPC_MODE_QPREPC125 "QPREPC125"
#define PREPC_MODE_QPREPC250 "QPREPC250"
#define PREPC_MODE_QPREPC500 "QPREPC500"
#define PREPC_MODE_SIM31 "SIM31"

// PREPC2K
#define PREPC_MODE_PREPC2K "PREPC2K"

// Q15
#define PREPC_MODE_Q15 "Q15"

// QRA64
#define PREPC_MODE_QRA64 "QRA64"
#define PREPC_MODE_QRA64A "QRA64A"
#define PREPC_MODE_QRA64B "QRA64B"
#define PREPC_MODE_QRA64C "QRA64C"
#define PREPC_MODE_QRA64D "QRA64D"
#define PREPC_MODE_QRA64E "QRA64E"

// ROS
#define PREPC_MODE_ROS "ROS"
#define PREPC_MODE_ROS_EME "ROS-EME"
#define PREPC_MODE_ROS_HF "ROS-HF"
#define PREPC_MODE_ROS_MF "ROS-MF"

// RTTY
#define PREPC_MODE_RTTY "RTTY"
#define PREPC_MODE_ASCI "ASCI"

// RTTYM
#define PREPC_MODE_RTTYM "RTTYM"

// SSB
#define PREPC_MODE_SSB "SSB"
#define PREPC_MODE_LSB "LSB"
#define PREPC_MODE_USB "USB"

// SSTV
#define PREPC_MODE_SSTV "SSTV"

// T10
#define PREPC_MODE_T10 "T10"

// THOR
#define PREPC_MODE_THOR "THOR"
#define PREPC_MODE_THOR_M "THOR-M"
#define PREPC_MODE_THOR4 "THOR4"
#define PREPC_MODE_THOR5 "THOR5"
#define PREPC_MODE_THOR8 "THOR8"
#define PREPC_MODE_THOR11 "THOR11"
#define PREPC_MODE_THOR16 "THOR16"
#define PREPC_MODE_THOR22 "THOR22"
#define PREPC_MODE_THOR25X4 "THOR25X4"
#define PREPC_MODE_THOR50X1 "THOR50X1"
#define PREPC_MODE_THOR50X2 "THOR50X2"
#define PREPC_MODE_THOR100 "THOR100"

// THRB
#define PREPC_MODE_THRB "THRB"
#define PREPC_MODE_THRBX "THRBX"
#define PREPC_MODE_THRBX1 "THRBX1"
#define PREPC_MODE_THRBX2 "THRBX2"
#define PREPC_MODE_THRBX4 "THRBX4"
#define PREPC_MODE_THROB1 "THROB1"
#define PREPC_MODE_THROB2 "THROB2"
#define PREPC_MODE_THROB4 "THROB4"

// TOR
#define PREPC_MODE_TOR "TOR"
#define PREPC_MODE_AMTORFEC "AMTORFEC"
#define PREPC_MODE_GTOR "GTOR"
#define PREPC_MODE_NAVTEX "NAVTEX"
#define PREPC_MODE_SITORB "SITORB"

// V4
#define PREPC_MODE_V4 "V4"

// VOI
#define PREPC_MODE_VOI "VOI"

// WINMOR
#define PREPC_MODE_WINMOR "WINMOR"

// WSPR
#define PREPC_MODE_WSPR "WSPR"

#endif
